// src/app/components/DummyProjectsData.tsx
// Adjust import path as needed

export const dummyProjects = [
    {
        id: 1,
        title: "Green Horizon Project",
        image: "/images/projects/mark.png",
        location: "East Africa",
        fundingProgress: 80,
        totalFunded: "$800K",
        goal: "$1M",
        category: "Carbon Credits",
        stage: "KGF Aligned",
        isTrending: true
    },
    {
        id: 2,
        title: "Blue Ocean Conservation",
        image: "/images/projects/mark.png",
        location: "South Pacific",
        fundingProgress: 92,
        totalFunded: "$920K",
        goal: "$1M",
        category: "Marine Protection",
        stage: "KGF Aligned",
        isTrending: true
    },
    {
        id: 3,
        title: "Solar Village Initiative",
        image: "/images/projects/mark.png",
        location: "West Africa",
        fundingProgress: 65,
        totalFunded: "$650K",
        goal: "$1M",
        category: "Renewable Energy",
        stage: "KGF Aligned",
        isTrending: true
    },
    {
        id: 4,
        title: "Reforestation Rwanda",
        image: "/images/projects/mark.png",
        location: "Rwanda",
        fundingProgress: 45,
        totalFunded: "$450K",
        goal: "$1M",
        category: "Carbon Credits",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 5,
        title: "Clean Water Kenya",
        image: "/images/projects/mark.png",
        location: "Kenya",
        fundingProgress: 30,
        totalFunded: "$300K",
        goal: "$1M",
        category: "Water Access",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 6,
        title: "Wind Energy Ethiopia",
        image: "/images/projects/mark.png",
        location: "Ethiopia",
        fundingProgress: 75,
        totalFunded: "$750K",
        goal: "$1M",
        category: "Renewable Energy",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 7,
        title: "Agroforestry Uganda",
        image: "/images/projects/mark.png",
        location: "Uganda",
        fundingProgress: 25,
        totalFunded: "$250K",
        goal: "$1M",
        category: "Agriculture",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 8,
        title: "Biofuel Tanzania",
        image: "/images/projects/mark.png",
        location: "Tanzania",
        fundingProgress: 60,
        totalFunded: "$600K",
        goal: "$1M",
        category: "Renewable Energy",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 9,
        title: "Mangrove Restoration Ghana",
        image: "/images/projects/mark.png",
        location: "Ghana",
        fundingProgress: 15,
        totalFunded: "$150K",
        goal: "$1M",
        category: "Carbon Credits",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 10,
        title: "Solar Schools Nigeria",
        image: "/images/projects/mark.png",
        location: "Nigeria",
        fundingProgress: 88,
        totalFunded: "$880K",
        goal: "$1M",
        category: "Education",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 11,
        title: "Waste-to-Energy Senegal",
        image: "/images/projects/mark.png",
        location: "Senegal",
        fundingProgress: 40,
        totalFunded: "$400K",
        goal: "$1M",
        category: "Waste Management",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 12,
        title: "Beekeeping Zambia",
        image: "/images/projects/mark.png",
        location: "Zambia",
        fundingProgress: 55,
        totalFunded: "$550K",
        goal: "$1M",
        category: "Agriculture",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 13,
        title: "Coral Reef Protection Madagascar",
        image: "/images/projects/mark.png",
        location: "Madagascar",
        fundingProgress: 70,
        totalFunded: "$700K",
        goal: "$1M",
        category: "Marine Protection",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 14,
        title: "Hydro Power Malawi",
        image: "/images/projects/mark.png",
        location: "Malawi",
        fundingProgress: 35,
        totalFunded: "$350K",
        goal: "$1M",
        category: "Renewable Energy",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 15,
        title: "Sanitation Zimbabwe",
        image: "/images/projects/mark.png",
        location: "Zimbabwe",
        fundingProgress: 20,
        totalFunded: "$200K",
        goal: "$1M",
        category: "Water Access",
        stage: "KGF Aligned",
        isTrending: false
    },
    // **10 MORE NEW PROJECTS (IDs 16-25)**
    {
        id: 16,
        title: "Biodiversity Congo Basin",
        image: "/images/projects/mark.png",
        location: "DRC",
        fundingProgress: 50,
        totalFunded: "$500K",
        goal: "$1M",
        category: "Conservation",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 17,
        title: "Solar Farms Morocco",
        image: "/images/projects/mark.png",
        location: "Morocco",
        fundingProgress: 85,
        totalFunded: "$850K",
        goal: "$1M",
        category: "Renewable Energy",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 18,
        title: "Irrigation Systems Sudan",
        image: "/images/projects/mark.png",
        location: "Sudan",
        fundingProgress: 28,
        totalFunded: "$280K",
        goal: "$1M",
        category: "Agriculture",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 19,
        title: "Forest Protection Cameroon",
        image: "/images/projects/mark.png",
        location: "Cameroon",
        fundingProgress: 62,
        totalFunded: "$620K",
        goal: "$1M",
        category: "Carbon Credits",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 20,
        title: "Clean Cookstoves Liberia",
        image: "/images/projects/mark.png",
        location: "Liberia",
        fundingProgress: 38,
        totalFunded: "$380K",
        goal: "$1M",
        category: "Clean Energy",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 21,
        title: "Water Purification Sierra Leone",
        image: "/images/projects/mark.png",
        location: "Sierra Leone",
        fundingProgress: 72,
        totalFunded: "$720K",
        goal: "$1M",
        category: "Water Access",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 22,
        title: "Wind Farms Namibia",
        image: "/images/projects/mark.png",
        location: "Namibia",
        fundingProgress: 18,
        totalFunded: "$180K",
        goal: "$1M",
        category: "Renewable Energy",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 23,
        title: "Soil Conservation Botswana",
        image: "/images/projects/mark.png",
        location: "Botswana",
        fundingProgress: 67,
        totalFunded: "$670K",
        goal: "$1M",
        category: "Agriculture",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 24,
        title: "Marine Sanctuary Mozambique",
        image: "/images/projects/mark.png",
        location: "Mozambique",
        fundingProgress: 42,
        totalFunded: "$420K",
        goal: "$1M",
        category: "Marine Protection",
        stage: "KGF Aligned",
        isTrending: false
    },
    {
        id: 25,
        title: "Bioenergy Angola",
        image: "/images/projects/mark.png",
        location: "Angola",
        fundingProgress: 53,
        totalFunded: "$530K",
        goal: "$1M",
        category: "Renewable Energy",
        stage: "KGF Aligned",
        isTrending: false
    }
];